version: '3.4'

services:
    back-end:
        build:
            context: back-end
        volumes:
            - ./back-end/db/:/app/db
        ports:
            - 8081:8081
    front-end:
        build:
            context: front-end
        ports:
            - 8080:8080
        environment:
            API_URI: http://back-end:8081
        depends_on:
            - back-end
